const themes = [
    {
        type: 'Dynamic',
        list: [
            {
                name: 'Tối',
                thumbnail: 'https://zmp3-static.zmdcdn.me/skins/zmp3-v6.1/images/theme/dark.jpg',
                details: {
                    primaryBg: "#1e1e1e",
                    menuSideBg: "#292929",
                    musicPlayBg: "#181818",
                    borderLayout: "hsla(0,0%,100%,0.1)",
                    borderDivideElement: "rgb(47, 47, 77)",
                    greenBanana: "#62c06e",
                    greenColor: 	"#2E8B57",
                    darkGreen: "#246e44",
                    darkCyan: "#109db6",
                    darkBlue: "#0000d8",
                    noneActiveColor: "#4c5262",
                    activeColor: "#36e2ec",
                    pinkColor: "#fc5c7d",
                    blueColor: "#6a82fb",
                    silverColor: 	"#C0C0C0",
                    textColor: "#fff",
                    subTextColor: "#9a9798",
                    orangeColor: "#fa8b26",
                    blueViolet: "#a742c6",
                    themeModalBg: "#282828",
                    backgroundImage: "url('../img/bg_mainpage.png')"
                }
            },
            {
                name: 'Xanh Da Trời',
                thumbnail: 'https://zmp3-static.zmdcdn.me/skins/zmp3-v6.1/images/theme/dynamic-blue.jpg',
                details: {
                    primaryBg: "#101f3f",
                    menuSideBg: "#1c2a49",
                    musicPlayBg: "#0a1835",
                    borderLayout: "hsla(0,0%,100%,0.1)",
                    borderDivideElement: "rgb(47, 47, 77)",
                    greenBanana: "#62c06e",
                    greenColor: 	"#2E8B57",
                    darkGreen: "#246e44",
                    darkCyan: "#109db6",
                    darkBlue: "#0000d8",
                    noneActiveColor: "#565e70",
                    activeColor: "#36e2ec",
                    pinkColor: "#fc5c7d",
                    blueColor: "#6a82fb",
                    silverColor: 	"#C0C0C0",
                    textColor: "#fff",
                    subTextColor: "#9a9798",
                    orangeColor: "#fa8b26",
                    blueViolet: "#a742c6",
                    themeModalBg: "#192f60",
                    backgroundImage: "url('../img/bg_mainpage.png')"
                }
            },
            {
                name: 'Hồng',
                thumbnail: 'https://zmp3-static.zmdcdn.me/skins/zmp3-v6.1/images/theme/dynamic-pink.jpg',
                details: {
                    primaryBg: "#800064",
                    menuSideBg: "#9b2180",
                    musicPlayBg: "#660050",
                    borderLayout: "hsla(0,0%,100%,0.1)",
                    borderDivideElement: "rgb(47, 47, 77)",
                    greenBanana: "#62c06e",
                    greenColor: 	"#2E8B57",
                    darkGreen: "#246e44",
                    darkCyan: "#109db6",
                    darkBlue: "#0000d8",
                    noneActiveColor: "#dadada",
                    activeColor: "#36e2ec",
                    pinkColor: "#fc5c7d",
                    blueColor: "#6a82fb",
                    silverColor: 	"#C0C0C0",
                    textColor: "#fff",
                    subTextColor: "#f80",
                    orangeColor: "#fa8b26",
                    blueViolet: "#a742c6",
                    themeModalBg: "#a22687",
                    backgroundImage: "url('../img/bg_mainpage.png')"
                }
            },
            {
                name: 'Nâu',
                thumbnail: 'https://zmp3-static.zmdcdn.me/skins/zmp3-v6.1/images/theme/dynamic-brown.jpg',
                details: {
                    primaryBg: "#57403b",
                    menuSideBg: "#604a45",
                    musicPlayBg: "#46332f",
                    borderLayout: "hsla(0,0%,100%,0.1)",
                    borderDivideElement: "rgb(47, 47, 77)",
                    greenBanana: "#62c06e",
                    greenColor: 	"#2E8B57",
                    darkGreen: "#246e44",
                    darkCyan: "#109db6",
                    darkBlue: "#0000d8",
                    noneActiveColor: "#d7d7d6",
                    activeColor: "#36e2ec",
                    pinkColor: "#fc5c7d",
                    blueColor: "#6a82fb",
                    silverColor: 	"#C0C0C0",
                    textColor: "#fff",
                    subTextColor: "#9a9798",
                    orangeColor: "#fa8b26",
                    blueViolet: "#a742c6",
                    themeModalBg: "#6f514c",
                    backgroundImage: "url('../img/bg_mainpage.png')"
                }
            },
            {
                name: 'Hồng Cánh Sen',
                thumbnail: 'https://zmp3-static.zmdcdn.me/skins/zmp3-v6.1/images/theme/pink-light.jpg',
                details: {
                    primaryBg: "#f9dbdb",
                    menuSideBg: "#fbe6e6",
                    musicPlayBg: "#f9c6c5",
                    borderLayout: "#afb9b9",
                    borderDivideElement: "rgb(47, 47, 77)",
                    greenBanana: "#62c06e",
                    greenColor: 	"#2E8B57",
                    darkGreen: "#246e44",
                    darkCyan: "#109db6",
                    darkBlue: "#0000d8",
                    noneActiveColor: "#289595",
                    activeColor: "#012658",
                    pinkColor: "#fc5c7d",
                    blueColor: "#6a82fb",
                    silverColor: 	"#C0C0C0",
                    textColor: "#32323d",
                    subTextColor: "#9a9798",
                    orangeColor: "#fa8b26",
                    blueViolet: "#a742c6",
                    themeModalBg: "#e1e8e8",
                    backgroundImage: "url('../img/bg_mainpage.png')"
                }
            }
        ]
    },
    {
        type: 'Màu Sắc',
        list: [
            {
                name: 'Tím',
                thumbnail: 'https://zmp3-static.zmdcdn.me/skins/zmp3-v6.1/images/theme/purple.jpg',
                details: {
                    primaryBg: "#170f23",
                    menuSideBg: "#231b2e",
                    musicPlayBg: "#120c1c",
                    borderLayout: "hsla(0,0%,100%,0.1)",
                    borderDivideElement: "rgb(47, 47, 77)",
                    greenBanana: "#62c06e",
                    greenColor: 	"#2E8B57",
                    darkGreen: "#246e44",
                    darkCyan: "#109db6",
                    darkBlue: "#0000d8",
                    noneActiveColor: "#4c5262",
                    activeColor: "#36e2ec",
                    pinkColor: "#fc5c7d",
                    blueColor: "#6a82fb",
                    silverColor: 	"#C0C0C0",
                    textColor: "#fff",
                    subTextColor: "#9a9798",
                    orangeColor: "#fa8b26",
                    blueViolet: "#a742c6",
                    themeModalBg: "#432275",
                    backgroundImage: "url('../img/bg_mainpage.png')"
                }
            },
            {
                name: 'Đỏ',
                thumbnail: 'https://zmp3-static.zmdcdn.me/skins/zmp3-v6.1/images/theme/red.jpg',
                details: {
                    primaryBg: "#731717",
                    menuSideBg: "#7a2323",
                    musicPlayBg: "#5c1212",
                    borderLayout: "hsla(0,0%,100%,0.1)",
                    borderDivideElement: "rgb(47, 47, 77)",
                    greenBanana: "#62c06e",
                    greenColor: 	"#2E8B57",
                    darkGreen: "#246e44",
                    darkCyan: "#109db6",
                    darkBlue: "#0000d8",
                    noneActiveColor: "#7885a8",
                    activeColor: "#36e2ec",
                    pinkColor: "#fc5c7d",
                    blueColor: "#6a82fb",
                    silverColor: 	"#C0C0C0",
                    textColor: "#fff",
                    subTextColor: "#9a9798",
                    orangeColor: "#fa8b26",
                    blueViolet: "#a742c6",
                    themeModalBg: "#883236",
                    backgroundImage: "url('../img/bg_mainpage.png')"
                }
            },
            {
                name: 'Xanh Lá',
                thumbnail: 'https://zmp3-static.zmdcdn.me/skins/zmp3-v6.1/images/theme/blue.jpg',
                details: {
                    primaryBg: "#124534",
                    menuSideBg: "#1e4e3e",
                    musicPlayBg: "#0e372a",
                    borderLayout: "hsla(0,0%,100%,0.1)",
                    borderDivideElement: "rgb(47, 47, 77)",
                    greenBanana: "#62c06e",
                    greenColor: 	"#2E8B57",
                    darkGreen: "#246e44",
                    darkCyan: "#109db6",
                    darkBlue: "#0000d8",
                    noneActiveColor: "#bec5c2",
                    activeColor: "#36e2ec",
                    pinkColor: "#fc5c7d",
                    blueColor: "#6a82fb",
                    silverColor: 	"#C0C0C0",
                    textColor: "#fff",
                    subTextColor: "#9a9798",
                    orangeColor: "#fa8b26",
                    blueViolet: "#a742c6",
                    themeModalBg: "#126e54",
                    backgroundImage: "url('../img/bg_mainpage.png')"
                }
            },
            {
                name: 'Xanh Biển',
                thumbnail: 'https://zmp3-static.zmdcdn.me/skins/zmp3-v6.1/images/theme/blue-light.jpg',
                details: {
                    primaryBg: "#1d375a",
                    menuSideBg: "#294162",
                    musicPlayBg: "#172c48",
                    borderLayout: "hsla(0,0%,100%,0.1)",
                    borderDivideElement: "rgb(47, 47, 77)",
                    greenBanana: "#62c06e",
                    greenColor: 	"#2E8B57",
                    darkGreen: "#246e44",
                    darkCyan: "#109db6",
                    darkBlue: "#0000d8",
                    noneActiveColor: "#5d6c7f",
                    activeColor: "#36e2ec",
                    pinkColor: "#fc5c7d",
                    blueColor: "#6a82fb",
                    silverColor: 	"#C0C0C0",
                    textColor: "#fff",
                    subTextColor: "#9a9798",
                    orangeColor: "#fa8b26",
                    blueViolet: "#a742c6",
                    themeModalBg: "#274a78",
                    backgroundImage: "url('../img/bg_mainpage.png')"
                }
            },
            {
                name: 'Xanh Nhạt',
                thumbnail: 'https://zmp3-static.zmdcdn.me/skins/zmp3-v6.1/images/theme/green-light.jpg',
                details: {
                    primaryBg: "#ced9d9",
                    menuSideBg: "#dde4e4",
                    musicPlayBg: "#b4d0d0",
                    borderLayout: "#afb9b9",
                    borderDivideElement: "rgb(47, 47, 77)",
                    greenBanana: "#62c06e",
                    greenColor: 	"#2E8B57",
                    darkGreen: "#246e44",
                    darkCyan: "#109db6",
                    darkBlue: "#0000d8",
                    noneActiveColor: "#289595",
                    activeColor: "#012658",
                    pinkColor: "#fc5c7d",
                    blueColor: "#6a82fb",
                    silverColor: 	"#C0C0C0",
                    textColor: "#32323d",
                    subTextColor: "#9a9798",
                    orangeColor: "#fa8b26",
                    blueViolet: "#a742c6",
                    themeModalBg: "#e1e8e8",
                    backgroundImage: "url('../img/bg_mainpage.png')"
                }
            }
        ]
    },
    {
        type: "Ca Sĩ",
        list: [
            {
                name: 'Justin Bieber',
                thumbnail: './assets/img/thumbnail_justinbieber.png',
                details: {
                    primaryBg: "#170f23",
                    menuSideBg: "#231b2e",
                    musicPlayBg: "#120c1c",
                    borderLayout: "hsla(0,0%,100%,0.1)",
                    borderDivideElement: "rgb(47, 47, 77)",
                    greenBanana: "#62c06e",
                    greenColor: 	"#2E8B57",
                    darkGreen: "#246e44",
                    darkCyan: "#109db6",
                    darkBlue: "#0000d8",
                    noneActiveColor: "#4c5262",
                    activeColor: "#36e2ec",
                    pinkColor: "#fc5c7d",
                    blueColor: "#6a82fb",
                    silverColor: 	"#C0C0C0",
                    textColor: "#fff",
                    subTextColor: "#9a9798",
                    orangeColor: "#fa8b26",
                    blueViolet: "#a742c6",
                    themeModalBg: "#432275",
                    backgroundImage: "url('../img/bg_justinbieber.png')"
                }
                
            },
            {
                name: 'Rose (Blackpink)',
                thumbnail: './assets/img/thumbnail_rose.png',
                details: {
                    primaryBg: "#170f23",
                    menuSideBg: "#231b2e",
                    musicPlayBg: "#120c1c",
                    borderLayout: "hsla(0,0%,100%,0.1)",
                    borderDivideElement: "rgb(47, 47, 77)",
                    greenBanana: "#62c06e",
                    greenColor: 	"#2E8B57",
                    darkGreen: "#246e44",
                    darkCyan: "#109db6",
                    darkBlue: "#0000d8",
                    noneActiveColor: "#4c5262",
                    activeColor: "#36e2ec",
                    pinkColor: "#fc5c7d",
                    blueColor: "#6a82fb",
                    silverColor: 	"#C0C0C0",
                    textColor: "#fff",
                    subTextColor: "#9a9798",
                    orangeColor: "#fa8b26",
                    blueViolet: "#a742c6",
                    themeModalBg: "#432275",
                    backgroundImage: "url('../img/bg_rose.png')"
                }
                
            },
            {
                name: 'Nguyễn Văn Giàu',
                thumbnail: './assets/img/thumbnail_vangiau.png',
                details: {
                    primaryBg: "#170f23",
                    menuSideBg: "#231b2e",
                    musicPlayBg: "#120c1c",
                    borderLayout: "hsla(0,0%,100%,0.1)",
                    borderDivideElement: "rgb(47, 47, 77)",
                    greenBanana: "#62c06e",
                    greenColor: 	"#2E8B57",
                    darkGreen: "#246e44",
                    darkCyan: "#109db6",
                    darkBlue: "#0000d8",
                    noneActiveColor: "#4c5262",
                    activeColor: "#36e2ec",
                    pinkColor: "#fc5c7d",
                    blueColor: "#6a82fb",
                    silverColor: 	"#C0C0C0",
                    textColor: "#fff",
                    subTextColor: "#9a9798",
                    orangeColor: "#fa8b26",
                    blueViolet: "#a742c6",
                    themeModalBg: "#432275",
                    backgroundImage: "url('../img/bg_vangiau.png')"
                }
                
            },
            {
                name: 'Sơn Tùng MTP',
                thumbnail: './assets/img/thumbnail_sontungmtp.png',
                details: {
                    primaryBg: "#170f23",
                    menuSideBg: "#231b2e",
                    musicPlayBg: "#120c1c",
                    borderLayout: "hsla(0,0%,100%,0.1)",
                    borderDivideElement: "rgb(47, 47, 77)",
                    greenBanana: "#62c06e",
                    greenColor: 	"#2E8B57",
                    darkGreen: "#246e44",
                    darkCyan: "#109db6",
                    darkBlue: "#0000d8",
                    noneActiveColor: "#4c5262",
                    activeColor: "#36e2ec",
                    pinkColor: "#fc5c7d",
                    blueColor: "#6a82fb",
                    silverColor: 	"#C0C0C0",
                    textColor: "#fff",
                    subTextColor: "#9a9798",
                    orangeColor: "#fa8b26",
                    blueViolet: "#a742c6",
                    themeModalBg: "#432275",
                    backgroundImage: "url('../img/bg_sontungmtp.png')"
                }
                
            },
            {
                name: 'DJ Snake',
                thumbnail: './assets/img/thumbnail_djsnake.png',
                details: {
                    primaryBg: "#170f23",
                    menuSideBg: "#231b2e",
                    musicPlayBg: "#120c1c",
                    borderLayout: "hsla(0,0%,100%,0.1)",
                    borderDivideElement: "rgb(47, 47, 77)",
                    greenBanana: "#62c06e",
                    greenColor: 	"#2E8B57",
                    darkGreen: "#246e44",
                    darkCyan: "#109db6",
                    darkBlue: "#0000d8",
                    noneActiveColor: "#4c5262",
                    activeColor: "#36e2ec",
                    pinkColor: "#fc5c7d",
                    blueColor: "#6a82fb",
                    silverColor: 	"#C0C0C0",
                    textColor: "#fff",
                    subTextColor: "#9a9798",
                    orangeColor: "#fa8b26",
                    blueViolet: "#a742c6",
                    themeModalBg: "#432275",
                    backgroundImage: "url('../img/bg_djsnake.png')"
                }
                
            }
        ]
    },
    {
        type: "Gradient",
        list: [
            {
                name: 'Khaki Aquamarine',
                thumbnail: './assets/img/thumbnail_gradient_1.png',
                details: {
                    primaryBg: "linear-gradient(45deg, #85FFBD 0%, #FFFB7D 100%)",
                    menuSideBg: "#8cffba",
                    musicPlayBg: "#fcfb7e",
                    borderLayout: "#afb9b9",
                    borderDivideElement: "rgb(47, 47, 77)",
                    greenBanana: "#62c06e",
                    greenColor: 	"#2E8B57",
                    darkGreen: "#246e44",
                    darkCyan: "#109db6",
                    darkBlue: "#0000d8",
                    noneActiveColor: "#289595",
                    activeColor: "#012658",
                    pinkColor: "#fc5c7d",
                    blueColor: "#6a82fb",
                    silverColor: 	"#C0C0C0",
                    textColor: "#32323d",
                    subTextColor: "#9a9798",
                    orangeColor: "#fa8b26",
                    blueViolet: "#a742c6",
                    themeModalBg: "#e1e8e8",
                    backgroundImage: "url('../img/bg_mainpage.png')"
                }
                
            },
            {
                name: 'Sandy Brown Violet',
                thumbnail: './assets/img/thumbnail_gradient_2.png',
                details: {
                    primaryBg: "linear-gradient( 102.4deg,  rgba(253,189,85,1) 7.8%, rgba(249,131,255,1) 100.3% )",
                    menuSideBg: "#fcb371",
                    musicPlayBg: "linear-gradient( 102.4deg,  rgba(253,289,85,1) 7.8%, rgba(149,131,255,1) 100.3% )",
                    borderLayout: "#afb9b9",
                    borderDivideElement: "rgb(47, 47, 77)",
                    greenBanana: "#62c06e",
                    greenColor: 	"#2E8B57",
                    darkGreen: "#246e44",
                    darkCyan: "#109db6",
                    darkBlue: "#0000d8",
                    noneActiveColor: "#289595",
                    activeColor: "#012658",
                    pinkColor: "#fc5c7d",
                    blueColor: "#6a82fb",
                    silverColor: 	"#C0C0C0",
                    textColor: "#32323d",
                    subTextColor: "#9a9798",
                    orangeColor: "#fa8b26",
                    blueViolet: "#a742c6",
                    themeModalBg: "#e1e8e8",
                    backgroundImage: "url('../img/bg_mainpage.png')"
                }
                
            },
            {
                name: 'Dark Cyan Green',
                thumbnail: './assets/img/thumbnail_gradient_3.png',
                details: {
                    primaryBg: "radial-gradient( circle 963px at 1.9% 5%,  rgba(0,193,80,1) 0%, rgba(0,112,198,1) 100.2% )",
                    menuSideBg: "linear-gradient( to bottom,  #00c052,  #00968e)",
                    musicPlayBg: "linear-gradient( to right,  #0070c0, #00ab70)",
                    borderLayout: "hsla(0,0%,100%,0.1)",
                    borderDivideElement: "rgb(47, 47, 77)",
                    greenBanana: "#62c06e",
                    greenColor: 	"#2E8B57",
                    darkGreen: "#246e44",
                    darkCyan: "#109db6",
                    darkBlue: "#0000d8",
                    noneActiveColor: "#4e4e83",
                    activeColor: "#08143d",
                    pinkColor: "#fc5c7d",
                    blueColor: "#6a82fb",
                    silverColor: 	"#C0C0C0",
                    textColor: "#fff",
                    subTextColor: "#23181c",
                    orangeColor: "#fa8b26",
                    blueViolet: "#a742c6",
                    themeModalBg: "#126e54",
                    backgroundImage: "url('../img/bg_mainpage.png')"
                }
                
            },
            {
                name: 'Brown Tomato',
                thumbnail: './assets/img/thumbnail_gradient_4.png',
                details: {
                    primaryBg: "linear-gradient( 135deg, #F05F57 10%, #360940 100%)",
                    menuSideBg: "linear-gradient( to bottom,  #f05f57,  #6f2448)",
                    musicPlayBg: "linear-gradient( to right,  #802c4a, #bc4750)",
                    borderLayout: "hsla(0,0%,100%,0.1)",
                    borderDivideElement: "rgb(47, 47, 77)",
                    greenBanana: "#62c06e",
                    greenColor: 	"#2E8B57",
                    darkGreen: "#246e44",
                    darkCyan: "#109db6",
                    darkBlue: "#0000d8",
                    noneActiveColor: "#0dd6f1",
                    activeColor: "#ff9",
                    pinkColor: "#fc5c7d",
                    blueColor: "#6a82fb",
                    silverColor: 	"#C0C0C0",
                    textColor: "#fff",
                    subTextColor: "#9a9798",
                    orangeColor: "#fa8b26",
                    blueViolet: "#a742c6",
                    themeModalBg: "#883236",
                    backgroundImage: "url('../img/bg_mainpage.png')"
                }
                
            }
        ]
    }
    
    
]